services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lle\ConfigBundle\:
        resource: '../../'

    Lle\ConfigBundle\Twig\ConfigExtension:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: [twig.extension]

    _instanceof:
        Lle\ConfigBundle\Repository\AbstractConfigRepository:
            calls:
                - setCache: ['@Psr\Cache\CacheItemPoolInterface']
