services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lle\ConfigBundle\:
        resource: '../../'

    Lle\ConfigBundle\Twig\ConfigExtension:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: [twig.extension]

    Lle\ConfigBundle\Crudit\Datasource\ConfigDatasource:
        arguments:
            $tenantService: '@?lle_config.tenant_service'

